# Generated by Django 5.0 on 2023-12-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_social_extra_data_myuser_social_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='social_extra_data',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='social_provider',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='social_uid',
        ),
    ]
