# Generated by Django 5.0 on 2023-12-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labexp', '0002_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='status',
            new_name='another_field',
        ),
    ]
