# Generated by Django 5.0 on 2023-12-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labexp', '0005_album_musician_delete_article_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='currency',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=3),
        ),
    ]
