# Generated by Django 5.0 on 2023-12-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labexp', '0007_musician_audio_alter_musician_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='audio',
            field=models.CharField(choices=[('Audio', [('vinyl', 'Vinyl'), ('cd', 'CD')]), ('Video', [('vhs', 'VHS Tape'), ('dvd', 'DVD')]), ('unknown', 'Unknown')], default='CD', max_length=255),
        ),
    ]
