# Generated by Django 5.0 on 2023-12-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labexp', '0008_alter_musician_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='audio',
            field=models.CharField(choices=[('Audio', [('vinyl', 'Vinyl'), ('cd', 'CD')]), ('Video', [('vhs', 'VHS Tape'), ('dvd', 'DVD')]), ('unknown', 'Unknown')], default='cd', max_length=255),
        ),
    ]
