# Generated by Django 5.0 on 2023-12-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labexp', '0013_comment_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comment',
            field=models.ManyToManyField(to='labexp.comment'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='comment',
            field=models.ManyToManyField(to='labexp.comment'),
        ),
    ]
