# Generated by Django 5.0 on 2023-12-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labexp', '0014_client_comment_todolist_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.ManyToManyField(blank=True, to='labexp.comment'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='comment',
            field=models.ManyToManyField(blank=True, to='labexp.comment'),
        ),
    ]
